//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.HimsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cl_ClinicName
    {
        public int Id { get; set; }
        public Nullable<int> Clid { get; set; }
        public string ClinicName { get; set; }
        public Nullable<bool> is_show { get; set; }
        public string type { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> FinDeptID { get; set; }
        public string RevnueGroup { get; set; }
    }
}
