//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.HimsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRosterforAppointment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> Entryid { get; set; }
        public string EntryIP { get; set; }
        public bool Status { get; set; }
        public Nullable<int> Cancelid { get; set; }
        public string Cancelip { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string Hospno { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Clinicid { get; set; }
        public Nullable<int> Docid { get; set; }
        public string StartTime { get; set; }
        public Nullable<int> TotalPatient { get; set; }
        public Nullable<int> MinutePerPatient { get; set; }
    }
}
