//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.HimsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccineStock
    {
        public int id { get; set; }
        public Nullable<int> NewStock { get; set; }
        public Nullable<int> AvaliableforPatient { get; set; }
        public Nullable<int> Used { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
