//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.InventryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Costcenter
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Projectid { get; set; }
        public Nullable<bool> isClose { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string uid { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUid { get; set; }
        public string ModifyIP { get; set; }
    }
}
