//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.InventryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AddBudget
    {
        public int id { get; set; }
        public Nullable<int> headID { get; set; }
        public string fY { get; set; }
        public Nullable<decimal> BudgetPro { get; set; }
        public Nullable<decimal> AlreadyExpense { get; set; }
        public Nullable<decimal> ThisExpense { get; set; }
        public Nullable<decimal> TotalExpense { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public bool status { get; set; }
        public string uid { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string IP { get; set; }
        public string remarks { get; set; }
        public bool adjustment { get; set; }
        public Nullable<decimal> Reallocate { get; set; }
    }
}
