//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.InventryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpo
    {
        public string fldpono { get; set; }
        public Nullable<System.DateTime> fldpodate { get; set; }
        public string fldstatus { get; set; }
        public string fldsupplierno { get; set; }
        public string fldpotype { get; set; }
        public Nullable<bool> fldpocompletestatus { get; set; }
        public decimal fldserialno { get; set; }
        public string fldCategoryNo { get; set; }
        public string PaymentTermNConditions { get; set; }
        public string Currency { get; set; }
        public string fldRemarks { get; set; }
        public string fldPo { get; set; }
        public string fldgst { get; set; }
        public string flduser { get; set; }
        public string fldip { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string IP { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifyIP { get; set; }
        public Nullable<int> fldSrdID { get; set; }
        public Nullable<System.DateTime> fldsrdDate { get; set; }
        public string InstrumentNo { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public bool isadvance { get; set; }
        public Nullable<int> Advanceuserid { get; set; }
        public Nullable<System.DateTime> advanceDate { get; set; }
        public string AdvanceIP { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<decimal> taxper { get; set; }
        public Nullable<decimal> taxAmount { get; set; }
        public Nullable<decimal> AmountexcTax { get; set; }
        public Nullable<int> ModeofPayment { get; set; }
        public string onlinetxNo { get; set; }
        public Nullable<System.DateTime> budgetDate { get; set; }
        public Nullable<int> budgetUserId { get; set; }
        public string budgetUserIp { get; set; }
        public Nullable<System.DateTime> POApproveDate { get; set; }
        public Nullable<int> POApproveUserID { get; set; }
        public string POApproveUserIp { get; set; }
        public Nullable<bool> isPoApprove { get; set; }
        public Nullable<int> isPoBudget { get; set; }
        public string ForwardedInformation { get; set; }
        public Nullable<int> fwdstatus { get; set; }
        public string EMinuteNo { get; set; }
        public bool isprinted { get; set; }
        public Nullable<System.DateTime> fldpaymentdate { get; set; }
        public Nullable<int> PayNo { get; set; }
        public string fldSRDPR { get; set; }
        public Nullable<bool> istaxPaid { get; set; }
        public string returnBackIP { get; set; }
        public Nullable<System.DateTime> checkPrintDate { get; set; }
        public string checkPrintIP { get; set; }
        public string checkPrintUser { get; set; }
    }
}
