//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePlacementDeductionDetail
    {
        public int PlacecmentDeductionDetailID { get; set; }
        public Nullable<int> PlacementID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DeductionID { get; set; }
        public Nullable<decimal> DeductionAmount { get; set; }
        public Nullable<bool> IsCheck { get; set; }
    }
}
