//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeExprienceDetail
    {
        public int EmployeeExprienceDetailID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FirmName { get; set; }
        public string Firmaddress { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public string Remarks { get; set; }
    }
}
