//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeearrierDetail
    {
        public int EmployeearrierDetalID { get; set; }
        public Nullable<int> EmployeearrierID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AllowanceDeductionID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
