//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducationDetail
    {
        public int EducationDetailid { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Degree { get; set; }
        public string Institute { get; set; }
        public string Boarduniversity { get; set; }
        public string ObtainMarks { get; set; }
        public string TotalMarks { get; set; }
        public string PassingYear { get; set; }
    }
}
