//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeNomineeDetail
    {
        public int nomineeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string NomineeName { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Relation { get; set; }
    }
}
