//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GLUserGroupDetail
    {
        public int UserGroupDetailID { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public Nullable<int> FormsID { get; set; }
        public Nullable<bool> Assign { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsNew { get; set; }
    
        public virtual GLUserGroup GLUserGroup { get; set; }
        public virtual UserForm UserForm { get; set; }
    }
}
