//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEmployeePlacementAllowancesDetail
    {
        public int LogID { get; set; }
        public Nullable<int> PlacementID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> AllowanceID { get; set; }
        public Nullable<decimal> AllowanceRate { get; set; }
        public Nullable<decimal> AllowanceAmount { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
