//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectActivityLog
    {
        public long Idlog { get; set; }
        public string ProjectIDs { get; set; }
        public string ServiceTypeID { get; set; }
        public string ServiceActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string CreatedIP { get; set; }
        public string Employeeid { get; set; }
        public Nullable<int> Modifedyid { get; set; }
        public Nullable<System.DateTime> Modifeddate { get; set; }
        public string Modifiedip { get; set; }
        public bool Status { get; set; }
        public Nullable<int> modifedEmployee { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string RelatedTo { get; set; }
    }
}
