//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxConfigurationDetail
    {
        public int DetailID { get; set; }
        public Nullable<int> TaxConfiguration { get; set; }
        public Nullable<decimal> AnualSalaryFrom { get; set; }
        public Nullable<decimal> AnualSalaryTo { get; set; }
        public Nullable<decimal> FixedAmount { get; set; }
        public Nullable<decimal> Percentage { get; set; }
    }
}
