//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BoardProceeding
    {
        public int MinuteSheetID { get; set; }
        public string MinuteSheetCode { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<System.DateTime> MinuteSheetDate { get; set; }
        public string Initiatedby { get; set; }
        public string Priority { get; set; }
        public string Type { get; set; }
        public string Subject { get; set; }
        public string HtmlBox { get; set; }
        public Nullable<int> ForwardTo { get; set; }
        public string ForInfo { get; set; }
        public bool inactive { get; set; }
        public Nullable<int> EntryID { get; set; }
        public string EntryIP { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<int> ModifiedID { get; set; }
        public string ModifiedIP { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int Status { get; set; }
        public Nullable<int> MinuteType { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Remarks { get; set; }
        public string InitiatedDepartment { get; set; }
        public Nullable<int> Displayfornew { get; set; }
        public string fldStatus { get; set; }
        public string ChairPerson { get; set; }
        public string President { get; set; }
        public bool SignMinute { get; set; }
        public string RoleInThisSheet { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string TimeofSign { get; set; }
        public string DateofSign { get; set; }
    }
}
