//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEminutePettyCashDetail
    {
        public int PettycashID { get; set; }
        public string EminuteCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool Inactive { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string IP { get; set; }
        public int UserID { get; set; }
        public bool isClear { get; set; }
    }
}
