//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeLoan
    {
        public int LoanID { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> RequestedAmount { get; set; }
        public Nullable<int> LoanType { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public Nullable<System.DateTime> PaymentStartDate { get; set; }
        public Nullable<System.DateTime> PaymentEndDate { get; set; }
        public Nullable<int> NoOfInstallments { get; set; }
        public string Remark { get; set; }
        public bool Inactive { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> EntryID { get; set; }
        public string EntryIP { get; set; }
        public Nullable<int> ModifiedID { get; set; }
        public string ModifiedIP { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<decimal> PerInstallment { get; set; }
        public bool FixnPercentage { get; set; }
    }
}
