//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEminuteEditlog
    {
        public int logid { get; set; }
        public string Eminutecode { get; set; }
        public string BeforeEdit { get; set; }
        public string AterEdit { get; set; }
        public string Ip { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
