//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempIonInfo
    {
        public int tempIonid { get; set; }
        public string htmlbox { get; set; }
        public string remarks { get; set; }
        public string IP { get; set; }
    }
}
