//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.AttendanceModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDeviceConfiguration
    {
        public int DeviceID { get; set; }
        public string Mac { get; set; }
        public string Location { get; set; }
        public bool Status { get; set; }
    }
}
