//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset_no
    {
        public long id { get; set; }
        public Nullable<long> Hosp_id { get; set; }
        public Nullable<long> year { get; set; }
        public Nullable<long> row_no { get; set; }
        public Nullable<long> uid { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
