//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetDocDetail
    {
        public int AssetDocID { get; set; }
        public Nullable<long> ServiceID { get; set; }
        public string AssetDescription { get; set; }
        public string PathDoc { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
