//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixed_Asset_SubCategory
    {
        public long Sub_Cat_Id { get; set; }
        public string Sub_Cat_Name { get; set; }
        public Nullable<long> Cat_Id { get; set; }
        public string prefix { get; set; }
        public Nullable<int> Uid { get; set; }
        public string User_Ip { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> TagNo { get; set; }
        public Nullable<int> MinuteSubTypeID { get; set; }
    }
}
