//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixed_Asset_Category
    {
        public long Cat_Id { get; set; }
        public string Cat_Name { get; set; }
        public Nullable<int> Uid { get; set; }
        public string User_Ip { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Hosp_ID { get; set; }
        public string Prefix { get; set; }
        public Nullable<bool> DepStatus { get; set; }
        public decimal DepreciationPerYear { get; set; }
        public string TagNo { get; set; }
        public Nullable<int> MinuteTypeID { get; set; }
    }
}
