//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EngineerDetail
    {
        public int id { get; set; }
        public string EngName { get; set; }
        public string FatherName { get; set; }
        public string CNIC { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
