//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAsset
    {
        public long id { get; set; }
        public string AssetId { get; set; }
        public string Assetoldtag { get; set; }
        public string AssetName { get; set; }
        public string AssetDesc { get; set; }
        public string AssetModel { get; set; }
        public string AssetManufacturer { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<long> SectionId { get; set; }
        public Nullable<int> supplierId { get; set; }
        public string AssetCondition { get; set; }
        public Nullable<int> financialYearId { get; set; }
        public string RV { get; set; }
        public Nullable<System.DateTime> RVDate { get; set; }
        public string JVBRV { get; set; }
        public Nullable<System.DateTime> JVBRVDate { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public Nullable<int> DayInUsed { get; set; }
        public Nullable<decimal> PurchasedPrice { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> convertPrice { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> depriciationRate { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<decimal> AssetSalvageValue { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public string ReceivedIp { get; set; }
        public Nullable<bool> ReceivedStatus { get; set; }
        public bool LogVarifyStatus { get; set; }
        public Nullable<long> LogVarifiedBy { get; set; }
        public Nullable<System.DateTime> LogVarifiedDate { get; set; }
        public string LogVarifiedIp { get; set; }
        public Nullable<bool> FinanceVarifiedStatus { get; set; }
        public Nullable<long> FinanceVarifiedBy { get; set; }
        public Nullable<System.DateTime> FinanceVarifiedDate { get; set; }
        public string FinanceVarifiedIp { get; set; }
        public Nullable<bool> AssetStatus { get; set; }
        public Nullable<bool> Desposal { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> Entrydate { get; set; }
        public Nullable<bool> IssuedStatus { get; set; }
        public Nullable<int> IssuebyID { get; set; }
        public Nullable<int> IssueToID { get; set; }
        public Nullable<System.DateTime> isseBYDate { get; set; }
        public Nullable<System.DateTime> issuetoDate { get; set; }
        public string IvNumber { get; set; }
        public Nullable<System.DateTime> ivDdate { get; set; }
        public string inspectionNo { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string PoNumber { get; set; }
        public Nullable<System.DateTime> PoDate { get; set; }
        public Nullable<System.DateTime> DateAson { get; set; }
        public string WDVD { get; set; }
        public string AccDepreciation { get; set; }
        public string DepreciationCharges { get; set; }
        public Nullable<bool> Capitalize { get; set; }
        public string Custodian { get; set; }
        public string chequeNo { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string VerifyRemarks { get; set; }
    }
}
