//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcurrency
    {
        public long curcode { get; set; }
        public string curname { get; set; }
        public string ip { get; set; }
        public string hospid { get; set; }
        public System.DateTime transdattim { get; set; }
        public Nullable<decimal> PKRrate { get; set; }
        public string status { get; set; }
        public string uid { get; set; }
    }
}
