//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDisposal
    {
        public long id { get; set; }
        public Nullable<long> AssetId { get; set; }
        public string AssetNo { get; set; }
        public Nullable<decimal> DepricaitedValue { get; set; }
        public string disposalType { get; set; }
        public string WriteOfReason { get; set; }
        public Nullable<decimal> SaleValue { get; set; }
        public string PaymentMode { get; set; }
        public string SoldReasons { get; set; }
        public string Buyer { get; set; }
        public string JvNo { get; set; }
        public Nullable<System.DateTime> JVDate { get; set; }
        public Nullable<int> disposalBy { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> VarifiedBy { get; set; }
        public Nullable<System.DateTime> varifiedDate { get; set; }
        public Nullable<int> userId { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public string chequeNo { get; set; }
        public Nullable<int> technicalClearcnce { get; set; }
        public Nullable<System.DateTime> technicalclearnceDate { get; set; }
        public Nullable<System.DateTime> DepricationDate { get; set; }
    }
}
