//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachine_Master
    {
        public int id { get; set; }
        public string GRNno { get; set; }
        public string itemID { get; set; }
        public string AssetNo { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public string MachineAmp { get; set; }
        public string PowerCategory { get; set; }
        public Nullable<System.DateTime> MainStartDate { get; set; }
        public Nullable<System.DateTime> MainEndDate { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentDesc { get; set; }
        public string SerialNo { get; set; }
        public string model { get; set; }
        public string condition { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerOrigin { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierTelephone { get; set; }
        public string SupplierMobile { get; set; }
        public string SupplierEmail { get; set; }
        public string MachineImage { get; set; }
        public string InspectedName { get; set; }
        public string InspectedDesignation { get; set; }
        public string InspectedRecomm { get; set; }
        public string InspectedRemarks { get; set; }
        public string HeadofDptName { get; set; }
        public string HeadofDptDesignation { get; set; }
        public string HeadofDptRecomm { get; set; }
        public string HeadofDptRemarks { get; set; }
        public string ServiceProvider { get; set; }
        public string EngContact { get; set; }
        public string EngEmail { get; set; }
        public Nullable<bool> OperatingManual { get; set; }
        public string OperatingManual_Path { get; set; }
        public Nullable<bool> ServiceManual { get; set; }
        public string ServiceManual_Path { get; set; }
        public Nullable<bool> UserManual { get; set; }
        public string UserManual_Path { get; set; }
        public Nullable<bool> SoftwareManual { get; set; }
        public string SoftwareManual_Path { get; set; }
        public Nullable<bool> logBook { get; set; }
        public string logBook_path { get; set; }
        public Nullable<bool> MaintenanceSchedule { get; set; }
        public Nullable<System.DateTime> CurrentMainDate { get; set; }
        public string SchedulePeriod { get; set; }
        public Nullable<System.DateTime> NextMainDueDate { get; set; }
        public Nullable<bool> status { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string IP { get; set; }
        public string ModifyUserID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyIP { get; set; }
        public string type { get; set; }
        public string UserAcceptanceName { get; set; }
        public string UserAcceptanceDesig { get; set; }
        public string UserAcceptanceRecomm { get; set; }
        public string UserAcceptanceRemarks { get; set; }
    }
}
