//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachine_Detail
    {
        public int id { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string voucherNo { get; set; }
        public string itemID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> status { get; set; }
        public string AssetNo { get; set; }
        public string type { get; set; }
    }
}
