//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovement
    {
        public long id { get; set; }
        public string AssetNo { get; set; }
        public Nullable<long> AssetId { get; set; }
        public Nullable<int> HospitalId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string TransferReason { get; set; }
        public Nullable<decimal> depricaitionValue { get; set; }
        public Nullable<long> TransferBy { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<bool> TransferStatus { get; set; }
        public Nullable<long> ReceivedBy { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<bool> ReceivedStatus { get; set; }
        public Nullable<long> VarifiedBy { get; set; }
        public Nullable<System.DateTime> VarifiedDate { get; set; }
        public Nullable<bool> VarfiedStatus { get; set; }
        public Nullable<int> entryBy { get; set; }
        public Nullable<System.DateTime> entryDate { get; set; }
        public string entryIp { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> CurrentLocation { get; set; }
        public Nullable<long> TransferFromId { get; set; }
        public Nullable<long> TransferToId { get; set; }
        public Nullable<int> aprovedid { get; set; }
        public Nullable<System.DateTime> Approveddate { get; set; }
        public string Custodian { get; set; }
    }
}
