//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMachine_Master_log
    {
        public int id { get; set; }
        public string MasterID { get; set; }
        public string AssetID { get; set; }
        public string AssetNo { get; set; }
        public Nullable<System.DateTime> WarrantyStartDate { get; set; }
        public Nullable<System.DateTime> WarrantyEndDate { get; set; }
        public string MachineAmp { get; set; }
        public string PowerCategory { get; set; }
        public Nullable<System.DateTime> MainStartDate { get; set; }
        public Nullable<System.DateTime> MainEndDate { get; set; }
        public string ServiceProvider { get; set; }
        public string EngContact { get; set; }
        public string EngEmail { get; set; }
        public string ImageUrl_1 { get; set; }
        public string ImageUrl_2 { get; set; }
        public string ImageUrl_3 { get; set; }
        public string ImageUrl_4 { get; set; }
        public Nullable<System.DateTime> CurrentMainDate { get; set; }
        public string SchedulePeriod { get; set; }
        public Nullable<System.DateTime> NextMainDueDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UserID { get; set; }
        public string IP { get; set; }
    }
}
