//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoleDetail
    {
        public int id { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string MenuName { get; set; }
        public Nullable<bool> isAllow { get; set; }
        public Nullable<bool> isNew { get; set; }
        public Nullable<bool> isedit { get; set; }
        public Nullable<bool> isdelete { get; set; }
        public Nullable<bool> isprint { get; set; }
    }
}
