//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoom
    {
        public int Rm_ID { get; set; }
        public string Room_Name { get; set; }
        public Nullable<int> Hospt_Code { get; set; }
        public Nullable<int> Dept_Code { get; set; }
    }
}
