//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public string Address { get; set; }
        public string phone { get; set; }
        public string cell { get; set; }
        public string email { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> userId { get; set; }
        public string ip { get; set; }
    }
}
