//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRandPayrollSystemModel.FixedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSection
    {
        public long id { get; set; }
        public string SectionName { get; set; }
        public Nullable<long> CatId { get; set; }
        public Nullable<long> Sub_Cat_id { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> Uid { get; set; }
        public string User_Ip { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<bool> status { get; set; }
        public string AccountNo { get; set; }
    }
}
